---
abstract: 'Network library for Snarl'
author:
  - 'Alan Berndt <alan@eatabrick.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Snarl
requires:
  Carp: 0
  IO::Socket: 0
  Readonly: 0
resources:
  homepage: https://github.com/bentglasstube/Net-Snarl/
  repository: git://github.com/bentglasstube/Net-Snarl.git
version: 1.09
